# Generated by Django 5.0.2 on 2025-03-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0006_meetup_date_meetup_organizer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='organizer_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
