# Generated by Django 5.0.2 on 2025-03-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0007_meetup_organizer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='phone',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
