# Generated by Django 5.0.2 on 2025-03-17 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0005_participant_meetup_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='date',
            field=models.DateField(default=datetime.date(2004, 8, 12)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetup',
            name='organizer_email',
            field=models.EmailField(default=datetime.date(2004, 8, 12), max_length=254),
            preserve_default=False,
        ),
    ]
